name: Mirror

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mirror
        uses: codewurker/yoast-plugin-mirror-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          yoast-url: ${{ secrets.YOAST_URL }}
          yoast-product-slug: yoast-seo-wordpress-premium
          plugin-basename: wordpress-seo-premium/wp-seo-premium.php
